eduNEXT/eox-core

- .circleci/config.yml
- eox_core/apps.py
- eox_core/edxapp_wrapper/backends/users_h_v1.py
- eox_core/edxapp_wrapper/tests/test_users.py
- eox_core/edxapp_wrapper/users.py
- eox_core/settings/common.py
- eox_core/settings/test.py
- requirements.txt
This PR adds the capacity to create users on a real & running edxapp.
Direct import from edxapp are done on selectable backends that should be tested against the specific branch of edx-platform that they target.
To select a backend the settings module from django conf and the plugin is used.
> User creation capability

- requirements.txt
This dependency was missing for the test environment.
It was working on circleci because of how prepared those environments are
> Adding a missing dependency

- eox_core/urls.py
- eox_core/views.py
This PR adds extra information to the info view
The git sha is there to test the integrity of the version number or to provide extra granularity in case the installed version does not match exactly with a release
> Adding git sha to the output of eox-info

- eox_core/views.py
This PR fixes the call to the git cmd line so that is actually returns the ID of the commit in the eox-core package instead of that of edx-platform
> Correcting git sha

- .pylintrc
- eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
We had to copy the internals of the create_course_enrollment function to use check_access=False instead of check_access=True when calling CourseEnrollment.enroll
> Allow invitation-only enrollments

- eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
To avoid issues such as enrolling in inexistent courses because the API user sends and invalid course ID (e.g uppercase course ID is written lowercase instead)
> Raising CourseNotFoundError

- README.md
Bash commands order was wrong (throws direnv: error .envrc file not found) now its not.
> Command order was wrong on README.md

- eox_core/edxapp_wrapper/backends/users_h_v1.py
This PR fixes a error ocurred when lms try to import a module named: contentstore, since contentstore is a module defined in the INSTALLED_APPS of cms.
> LLPA-20 - Add/Remove instructor user - patch-1

- .circleci/config.yml
This PR simply raises the minimum limit for coverage to 60% excluding the backends
> Guarantee the limit at the current coverage

- eox_core/api/v1/serializers.py
- eox_core/api/v1/tests/test_enrollments.py
The purpose of this PR is to patch the missing email field of EnrollmentQuerySerializer:
> Add missing email field to EnrollmentQuerySerializer

- eox_core/api/v1/tests/test_enrollments.py
- eox_core/api/v1/views.py
- eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
This PR refactors a bit the logic for POST and PUT to:
- make the underlying functions require a user as a parameter, removing the need for 3 different implementations of get_edxapp_user
- have a function to update/create 1 single record in the view, where the required user param is explicitly passed to the underlying function
- support the capacity to respond in bulk to the bulk responses when one or more end in errors
> More standard methods por POST & PUT

- eox_core/api/v1/serializers.py
- eox_core/api/v1/tests/test_coursekey.py
- eox_core/api/v1/tests/test_enrollments.py
- eox_core/edxapp_wrapper/backends/coursekey_h_v1.py
- eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
- eox_core/edxapp_wrapper/coursekey.py
- eox_core/edxapp_wrapper/tests/test_coursekey.py
- eox_core/settings/aws.py
- eox_core/settings/common.py
- eox_core/settings/test.py
The purpose of this PR is to add the Course id validations when performing serializations to clean up redundant validations across views:
> Course id validation

- eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
This PR changes the response of the enrollments API. If there is no message to show, we return the name of the class instead. This alone will give us a lot of information at the API consumer.
Also we now don't fail when the enrollment_attribute assignment fails for the response.
This PR solves an edge case that we found on the ticket #7568.
> Making the errors of the CourseEnrollments be a lot more useful.

- eox_core/edxapp_wrapper/backends/users_h_v1.py
- eox_core/edxapp_wrapper/backends/users_h_v1_test.py
- eox_core/edxapp_wrapper/users.py
- eox_core/pipeline.py
- eox_core/tests/test_pipeline.py
This PR adds a function to the plugin than can be called on the TPA_SAML_PIPELINE
> Adding pipeline function to make sure users have a profile model

- README.md
- eox_core/settings/aws.py
- eox_core/settings/common.py
- setup.py
This PR adds Sentry integration support through eox-core installation with extras_require option.
The plugin installation must be as fllows:
`pip install git+https://github.com/eduNEXT/eox-core.git@v2.7.0#egg=eox-core==2.7.0[sentry]`
This will install the sentry SDK to enable the configuration. The readme file was updated to include details on how to enable sentry integration.
> Adding sentry integration

- eox_core/edxapp_wrapper/backends/users_h_v1.py
Using conf helpers to get the eox-core api users sources instead of global settings
@morenol 
@Squirrel18
> Configuration helpers fix

- eox_core/api/v1/serializers.py
- eox_core/edxapp_wrapper/backends/users_h_v1.py
- eox_core/edxapp_wrapper/backends/users_h_v1_test.py
- eox_core/edxapp_wrapper/backends/users_i_v1.py
- eox_core/edxapp_wrapper/users.py
- eox_core/settings/common.py
In ironwood the max length allowed for a username is 150. 
I thought that we could make use of EOX_CORE_USERS_BACKEND instead of add a new setting for this.
I changed the default of settings.EOX_CORE_USERS_BACKEND to the ironwood version
> Use 150 as username max length in Ironwood

- setup.py
Add extra dependency to social_core[openidconnect] in order to install python-jose if needed with 
eox-core[tpa]
> Add social_core[openidconnect] as extra requirement

- eox_core/settings/aws.py
This PR removes Sentry celery integration. This action is performed to fix an issue with the **export_csv_data** task from Poll xblock.
> Removing Sentry celery integration because of Poll task error

- eox_core/integrations/sentry.py
- eox_core/settings/aws.py
- eox_core/settings/common.py
This PR implements a callable to ignore specific exceptions to be sent to sentry.io service. The motivation behind this PR is the fact that Sentry dashboard gets a bit noisy with lots of exception events that are not relevant since they're not truly errors.
The exceptions can be ignored based on exception class match or last traceback text regex match
@diegomillan 
@morenol 
@felipemontoya
> Filtering sentry exceptions based on traceback text regex matches

- .circleci/config.yml
Use circleci matrix and test using python version of Juniper.
I am using python3.5.8 and python2.7.16 because the docker images python2.7-node and python3.5-node have node12.0.0 and it is currently failing (I think that we have to solve that for juniper since in juniper the node version is 12.0.0 and in ironwood it is V8.9.3). 
These images are using node version: 10.16.3 (just like the image that we were using).
I am also using the stretch debian base image since it is the image compatible with ubuntu16.04.
> Test using the python version used in juniper. Use circleci matrix

- eox_core/edxapp_wrapper/backends/users_h_v1.py
The field USERNAME_MAX_LENGTH was removed in this https://github.com/eduNEXT/eox-core/pull/102, this revert that change
> Revert USERNAME_MAX_LENGTH 

- eox_core/api/v1/serializers.py
- eox_core/api/v1/tests/test_users.py
- eox_core/api/v1/urls.py
- eox_core/api/v1/views.py
- eox_core/settings/common.py
- eox_core/settings/test.py
This PR adds patch method to the new view EdxappUserUpdater used to update users fields
This is a response to the necessity of updating the password and the field is_active using eox-core.
> Added patch method to edit edxapp users

- requirements/base.in
- requirements/base.txt
- requirements/django.txt
- requirements/django22.txt
- requirements/test.txt
- requirements/tox.txt
django-oauth-provider has problems when it is installed ironwood. (in ironwood it is used edx-django-oauth-provider)
> Do not install django-oauth-provider

- eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
This PR fixes the following error in Juniper:
This error was raised because in juniper enrollments API is located in /openedx/core/djangoapps/enrollments  and not in /common/djangoapps/enrollment. This was done in edx/edx-platform//pull/20702
> Fix enrollment import error in Juniper

- eox_core/api/data/v1/filters.py
- requirements/base.in
- requirements/base.txt
- requirements/constraints.txt
- requirements/django.txt
- requirements/test.txt
**Description and justification**
This PR fixes users'/course enrollment/ generated certificates/proctored exams filter error, caused by django-filter forward compatibility issue. Also, makes it backward compatible.
The main issue that we have here is that in django-filter v1.0.4 -version used in Ironwood- there's a keyword `name` that was deprecated after v2.0.0 -Juniper uses v2.2.0-, then or we use the deprecated keyword `name` or we use the replacement `field_name`. 
Solution: 
Change name to field_name and change Django-filter to a version != than 1.0.4 when using python 2.7. Version 1.1.0 supports name and field_name keyword: https://github.com/carltongibson/django-filter/blob/1.1.0/django_filters/filters.py#L92
> Fix django-filters in Juniper

- CHANGELOG.rst
- eox_core/api/v1/views.py
That permission doesn't make a lot of sense since this view returns the current user information and doesn't make anything else, and due to request.user is set by BearerAuthentication or SessionAuthentication the information returned always will belong to the current user.
> Remove api user info permission.

- CHANGELOG.rst
- eox_core/api/v1/views.py
revert changes of https://github.com/eduNEXT/eox-core/pull/121 since the view my_user_info in https://github.com/edx/edx-platform/blob/master/lms/djangoapps/mobile_api/users/views.py  already returns the necessary data without special permissions.
> Add EoxCoreAPIPermission to UserInfo APIView

- eox_core/tests/integration/README.rst
- eox_core/tests/integration/test_data
- eox_core/tests/integration/test_enrollment_integration.py
In addition to the unit tests that were already present with this PR it will now be possible to test al CRUD operations against a production, staging or local server. The suite uses a `test_data` file to handle the configuration of the tests. Make sure to edit this file depending on what you are wanting to do. A README with detailed instructions on how to run the tests is also included.
> Add a new suite of integration tests

- CHANGELOG.rst
- eox_core/api/v1/serializers.py
- eox_core/api/v1/views.py
- eox_core/api_schema.py
- eox_core/urls.py
- requirements/base.in
- requirements/test.txt
The current documentation is no easily discoverable, with this PR with can make our documentation public and of easy access from any site that uses eox-core. The main benefits are:
1. Live documentation, can perform interactive requests.
2. Swagger it's [already](https://github.com/edx/edx-platform/pull/21207) on the platform.
3. Can be used to produce static documentation.
(2021/01/11 edit): Some test requirements were not correctly upgraded on #126, so I also added them.
> Add swagger support for documentation.

- eox_core/edxapp_wrapper/backends/users_h_v1_test.py
- eox_core/edxapp_wrapper/backends/users_j_v1.py
- eox_core/edxapp_wrapper/users.py
- eox_core/pipeline.py
- eox_core/tests/test_pipeline.py
At the creation of new users through some TPA providers, some of them are created with an unusable password, a user with an unusable password cannot login if the common.djangoapps.third_party.pipeline.set_logged_in_cookies step is enabled.
This new pipeline step will prevent that from happening since all the users created in the auth pipeline will have an usable password.
> feat(tpa): create pipeline step to ensure creation of users with usable password

- eox_core/edxapp_wrapper/backends/users_h_v1_test.py
- eox_core/edxapp_wrapper/backends/users_j_v1.py
- eox_core/edxapp_wrapper/users.py
- eox_core/pipeline.py
- eox_core/tests/test_pipeline.py
In this PR we are adding an UserAttribute record to indicate that a password was generated to a user on creation.
> Add user attribute record for auto_password_via_tpa_pipeline

- eox_core/api/support/v1/serializers.py
- eox_core/api/support/v1/tests/test_users.py
- eox_core/api/support/v1/urls.py
- eox_core/api/support/v1/views.py
- eox_core/edxapp_wrapper/backends/comments_service_users_j_v1.py
- eox_core/edxapp_wrapper/comments_service_users.py
- eox_core/settings/common.py
- eox_core/settings/production.py
This feature adds a new endpoint that handles the replacement of usernames.
Allows updating an Edxapp user's Username along with the forum associated User (comments_service User).
> feat: Replace Username endpoint.

- eox_core/edxapp_wrapper/backends/users_l_v1.py
This import is used by the users wrapper and gave this error:
```
File "/edx/src/edxapp/eox-core/eox_core/edxapp_wrapper/users.py", line 97, in get_username_max_length
return backend.USERNAME_MAX_LENGTH
AttributeError: module 'eox_core.edxapp_wrapper.backends.users_l_v1' has no attribute 'USERNAME_MAX_LENGTH'
```
> fix: add USERNAME_MAX_LENGTH not used import

- eox_core/edxapp_wrapper/backends/enrollment_l_v1.py
Missing backend for enrollment that fixes: student/course_mode relative imports. Backend tested using swagger API docs.
> fix: add missing backends for lilac release

- CHANGELOG.rst
- eox_core/social_tpa_backends.py
This PR overrides a method from OpenIdConnect backend to allow us getting OIDC configuration per instance instead of per class
> fix: fix cache issue with ConfigurableOpenIdConnectAuth backend

- eox_core/social_tpa_backends.py
This PR adds an override method to the OIDC custom backend. The method adds useful information to the extra_data field from the UserSocialAuth model.
1. OIDC configuration
2. There's a pipeline step called `load_extra_data` that sets the new info every time the OIDC pipeline is executed (eg. when login in). This pipeline step belongs to the `DEFAULT_AUTH_PIPELINE`. So, log in to the site using the OIDC provider
Check extra_data and you'll get:
More context: https://3.basecamp.com/3966315/buckets/8050706/todos/3834823891
> feat: add override extra_data method to OIDC

- CHANGELOG.rst
- eox_core/social_tpa_backends.py
This PR adds debug mode when loading extra_data during the Auth pipeline execution. It also wraps get_user_details in try-except which allows saving information even when failing.
> refactor: add debug mode when loading extra_data

- CHANGELOG.rst
- eox_core/api/v1/serializers.py
- eox_core/api/v1/tests/test_users.py
- eox_core/api/v1/views.py
- eox_core/settings/common.py
- eox_core/utils.py
This PR allows updating the UserProfile fields considered as 'safe'
These "safe" fields are defined in the setting  EOX_CORE_USER_UPDATE_SAFE_FIELDS
A modification was also made to the update user endpoint to allow filtering the user by _username_ or _email_
> feat: Allow adding profile fields when updating a user

- requirements/base.in
The new release of api-doc-tools breaks python3.5
> fix: pin edx-api-doc-tools. 1.4.3 isn't compatible with python3.5

- CHANGELOG.rst
- eox_core/api/v1/serializers.py
Currently, the EdxappExtendedUserSerializer includes only the EDNX_CUSTOM_REGISTRATION_FIELDS that are also in the setting  "extended_profile_fields"
> fix: EdxappExtendedUserSerializer to include all  "EDNX_CUSTOM_REGISTRATION_FIELDS"

- eox_core/edxapp_wrapper/backends/users_j_v1.py
When importing `from eox_core.edxapp_wrapper.signals import post_register` I had this issue:
```
************* Module eox_core.edxapp_wrapper.backends.users_j_v1
eox_core/edxapp_wrapper/backends/users_j_v1.py:46:0: C0411: third party import "from student.helpers import do_create_account" should be placed before "from eox_core.edxapp_wrapper.signals import post_register" (wrong-import-order)
eox_core/edxapp_wrapper/backends/users_j_v1.py:47:0: C0411: third party import "from student.models import CourseEnrollment" should be placed before "from eox_core.edxapp_wrapper.signals import post_register" (wrong-import-order)
eox_core/edxapp_wrapper/backends/users_j_v1.py:46:0: C0412: Imports from package student are not grouped (ungrouped-imports)
```
Pretty easy to fix, but after doing it -I ran …
> fix: fix pylint conflicts with isort

- CHANGELOG.rst
- eox_core/edxapp_wrapper/backends/users_j_v1.py
PR #162 was closed in favor of this one.
This PR sends a signal after the user registration through `POST /eox-core/api/v1/user/`.  The signal is placed in a similar location as when registering through the LMS `/register` page, here is the reference: https://github.com/eduNEXT/edunext-platform/pull/510. It uses a backend to import the signal.
Context: https://3.basecamp.com/3966315/buckets/8050706/todos/3933592446
> feat: send signal after user registration through API

- CHANGELOG.rst
- eox_core/edxapp_wrapper/backends/coursekey_h_v1.py
- eox_core/edxapp_wrapper/backends/courses_h_v1.py
This PR wraps course and coursekey backends in a try-except block to avoid import errors when executing tests in other packages
> fix: wrap openedx imports in try-except block to avoid import errors

- CHANGELOG.rst
- eox_core/api/v1/serializers.py
- eox_core/api/v1/views.py
Documentation changes:
1. I added information about the enrollment force flag
2. Add force to EdxappCourseEnrollmentQuerySerializer
3. Use EdxappCourseEnrollmentQuerySerializer in `post` docs 
I got the information about the `force` by comparing the behavior of the two functions `_force_create_enrollment `and `_create_or_update_enrollment` in `eox-core/eox_core/edxapp_wrapper/backends/enrollment_h_v1.py`. This last function raises several exceptions such as:
EnrollmentClosedError
CourseFullError
AlreadyEnrolledError
and it also verifies that the enrollment mode belongs to the modes allowed by the course, while the force function skips them.
> docs: add enrollment force doc and change serializer for response doc

- CHANGELOG.rst
- eox_core/edxapp_wrapper/backends/third_party_auth_j_v1.py
- eox_core/edxapp_wrapper/third_party_auth.py
- eox_core/middleware.py
- eox_core/settings/common.py
- eox_core/settings/production.py
- eox_core/settings/test.py
During the third party authentication process there are some errors that are not correctly handled and result in a misleading 500 error page. 
As far as we know, this issue happens under any of this three conditions, so far:
1. The connection with the Identity Provider (IdP) results in an HTTP Error. See [social_core/backends/base.py](https://github.com/python-social-auth/social-core/blob/29cbbd22b98d81d569a886b1cc0bd9a316cd124f/social_core/backends/base.py#L237)
2. The pipeline step [`safer_associate_by_email`](https://github.com/eduNEXT/eox-tenant/blob/87906d31fdc3c2012514a9d6fc57a1277f49f6df/eox_tenant/pipeline.py#L15) raises `EoxTenantAuthException` when trying to [associate a staff/admin account ](https://github.com/eduNEXT/eox-tenant/blob/87906d31fdc3c2012514a9d6fc57a1277f49f6df/eox_ …
> feat(TPA): Add middleware to handle TPA exceptions

- CHANGELOG.rst
- eox_core/api/v1/views.py
This PR adds the save_all_parameters arg to the Users API, also adds the filter_data fields to the enrollments API
For more information about these changes https://github.com/eduNEXT/eox-audit-model/pull/12
**UPDATE**: Everything was successfully tested on stage.
> feat: add save_all_parameters and filter_data to eox-audit-model decorators

- CHANGELOG.rst
- eox_core/social_tpa_backends.py
This PR truncates the user's first_name sent by the identity provider to avoid exceeding the Django limit.
**Before**
Error 500:
**After**
Registers the user and:
The screenshots were taken after testing on stage.
> fix: truncate OIDC first_name to field max length

- CHANGELOG.rst
- eox_core/social_tpa_backends.py
This PR avoids failure when the first name is not sent by the provider
> fix: avoid failure when first_name is missing

- eox_core/settings/common.py
- eox_core/settings/production.py
Sentry allows for setting the `environment` attribute to identify in which stage of deployment an error event occurs. This can help with determining why an error happened and the urgency required to diagnose and resolve an issue.
> Exposing the option to set the deployment environment for Sentry

- eox_core/edxapp_wrapper/backends/users_l_v1.py
- eox_core/settings/common.py
After the [support for lilac](https://github.com/eduNEXT/eox-core/pull/143), there were some additions to the Users backend for Juniper. This PR updates the Users backend for Lilac with these changes.
Additions:
- https://github.com/eduNEXT/eox-core/commit/d83d1cbbfa0599585f0dade5532065acbbe16501
- https://github.com/eduNEXT/eox-core/commit/779c2301ef4a88d0d3869c71ad8876fac550f73b
Also, the default backends were changed to the Lilac backends (breaking change)
**Note**: we are going to open a different issue to fix the npm dependencies for python3.8 tests
> fix: Update Users backend for Lilac

- CHANGELOG.rst
- README.rst
This PR updates the plugin readme with the openedx compatibility notes
**Note**: we are going to open a different issue to fix the npm dependencies for python3.8 tests
> docs: add compatibility notes to readme

- .github/workflows/labeler.yml
These commits add the labeler action to the GitHub workflows with the purpose of checking one of the steps of the definition of done.
- The PR doesn't have more than 1000 lines.
You can find the Github action repository & documentation here:
https://github.com/CodelyTV/pr-size-labeler
> Add labeler action to github workflows

- .github/workflows/bump_version.yml
These commits add the bump version action to the GitHub workflows with the purpose of checking one of the steps of the definition of done.
- The feature is in a new release version.
```
<type>(<scope>): <short summary>
│       │             │
│       │             └─⫸ Summary in present tense. Not capitalized. No period at the end.
│       │
│       └─⫸ Commit Scope: animations|bazel|benchpress|common|compiler|compiler-cli|core|
│                          elements|forms|http|language-service|localize|platform-browser|
│                          platform-browser-dynamic|platform-server|router|service-worker|
│                          upgrade|zone.js|packaging|changelog|docs-infra|migrations|ngcc|ve|
│                          devtools
│
└─⫸ Commit Type: …
```
> ci: add bumpversion action to github workflows

- .github/workflows/commitlint.yml
- commitlint.config.js
These commits add the bump version action to the GitHub workflows with the purpose of checking one of the steps of the definition of done.
- The commits on the PR respect the commit convention.
```
[
'build',
'ci',
'docs',
'feat',
'fix',
'perf',
'refactor',
'revert',
'style',
'test'
]
```
```sh
echo "foo: some message" # fails
echo "fix: some message" # passes
```
```
'lowerCase'
```
```sh
echo "FIX: some message" # fails
echo "fix: some message" # passes
```
```
'lowerCase'
```
```sh
echo "fix(SCOPE): some message" # fails
echo "fix(scope): some message" # passes
```
```
72
```
```sh
echo "fix: some message that is way too long and breaks the line max-length by several characters" # fails
echo "fix: some message" # passes
```
More info:
> [Conventional Commits Message - …
> ci: add commitlint action to github workflows

- .github/workflows/bump_version.yml
This commit fixes the problem with **Changelog Update Action** adding a conditional to run that job only if exists a new tag.
- [Bump version #3](https://github.com/eduNEXT/eox-core/actions/runs/1865807381)
> ci: add conditional to run changelog update action

- eox_core/edxapp_wrapper/backends/coursekey_m_v1.py
- eox_core/settings/common.py
[get_current_site_orgs()](https://github.com/openedx/edx-platform/blob/open-release/lilac.master/openedx/core/djangoapps/site_configuration/helpers.py#L216) obtains the current site orgs getting first the current site:
which doesn't exist in async processes. So, this adds an alternative: if the current org is not found then try getting them directly from the site settings.
I'm currently testing this with an async task that enrolls users into a course. It's in a private repository, reach out if you want to test it out.
I found this issue while trying to enroll users in a course using an async task and configuring the site with course_org_filter. With this change, it's working correctly.
> fix: get settings course_org_filter when validating org for async proc

- requirements/base.in
Reverts eduNEXT/eox-core#204 for not complying with [OEP 18](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0018-bp-python-dependencies.html)
> Revert "chore: add openedx_events to requirements."

- eox_core/edxapp_wrapper/backends/users_j_v1.py
- eox_core/edxapp_wrapper/backends/users_l_v1.py
- eox_core/edxapp_wrapper/backends/users_m_v1.py
In this PR we make some changes to the [create_edxapp_user()](https://github.com/eduNEXT/eox-core/blob/master/eox_core/edxapp_wrapper/backends/users_m_v1.py#L104) in order to make the extra registration fields optional when registering a new user un edxapp.
Three conditions are checked in order to be able to skip these extra registration fields:
1. The skip_extra_registration_fields field is sent in the data for the account creation as True.
2. The user making the request is staff.
3. The data received in the parameters does not contain any of the REGISTRATION_EXTRA_FIELDS configured for the microsite.
In case any of these conditions are not met, the function will request the extra registration fields to be sent for the creation of the new user.
In PR #223 we are implementing an endpoint …
> feat: Make extra registration fields optional in during edxapp account creation

- eox_core/api/support/v1/serializers.py
- eox_core/api/support/v1/tests/test_oauth_applications.py
- eox_core/api/support/v1/urls.py
- eox_core/api/support/v1/views.py
- eox_core/settings/common.py
- eox_core/tests/test_utils.py
- eox_core/utils.py
In this PR we add a new endpoint in the support API that creates a new [Oauth Application in edxapp](https://openedx.edunext.co/admin/oauth2_provider/application/)
Request example
```
`POST <domain>/eox-core/support-api/v1/oauth-application/`
body: {
"user": {
"fullname": "John Doe",
"email": "johndoe@example.com",
"username": "johndoe",
"permissions": ["can_call_eox_core", "can_call_eox_tenant"]
},
"redirect_uris": "http://testing-site.io/ http://testing-site.io",
"client_type":"confidential",
"authorization_grant_type":"client-credentials",
"name": "test-application",
"skip_authorization": true
}
```
In order to create a valid Application, the method has to perform multiple operations:
1. Create a new edxapp user, who will be the owner of the Application. In case there is already a user …
> feat: add endpoint to generate Oauth Application

- eox_core/edxapp_wrapper/backends/enrollment_l_v1.py
This PR is to solve https://github.com/eduNEXT/eox-core/issues/240
You can try to enroll user to a course twice, with this fix, in the second enroll it show the the error message correctly:
Otherwise:
> fix: UnboundLocalError for enrollment backend

- README.rst
- eox_core/settings/common.py
- eox_core/settings/production.py
This PR fixes the issue #247 
Set the variable `EOX_CORE_SENTRY_EXTRA_OPTIONS` to any custom param that sentry accepts
> feat: allow sentry to receive extra params

- eox_core/integrations/sentry.py
Some hint in exception dont have `log_record` so exc_text is `""`
Log record info now for sentry seems to be for breadcrumbs. Eox core Sentry config is using `before_send` and not `before_breadcrumbs` so some exceptions are managed without the log_record. https://docs.sentry.io/platforms/python/guides/django/configuration/filtering/hints/ So the self.exc_text is `''`.
If this is empty regexes don't make anything in
https://github.com/eduNEXT/eox-core/blob/v6.1.0/eox_core/integrations/sentry.py#L154 so this change add `exc_value` if nothing is in log_records, the idea is to could compare at least with the str of the `exc_value`.
Regex doesn't work for exceptions with higher uses like Django exceptions.
Eg. When a Django model uses a get and I want to ignore it, I want to ignore only one …
> feat: add string represantion of exc_value to exc_text

- eox_core/integrations/sentry.py
Some hint in exception dont have `log_record` so exc_text is `""`
Log record info now for sentry seems to be for breadcrumbs. Eox core Sentry config is using `before_send` and not `before_breadcrumbs` so some exceptions are managed without the log_record. https://docs.sentry.io/platforms/python/guides/django/configuration/filtering/hints/ So the self.exc_text is `''`.
If this is empty regexes don't make anything in
https://github.com/eduNEXT/eox-core/blob/v6.1.0/eox_core/integrations/sentry.py#L154 so this change add `exc_value` if nothing is in log_records, the idea is to could compare at least with the str of the `exc_value`.
Regex doesn't work for exceptions with higher uses like Django exceptions.
Eg. When a Django model uses a get and I want to ignore it, I want to ignore only one …
> feat: add string represantion to exc_value

- eox_core/edxapp_wrapper/backends/users_m_v1.py
Enable the custom_reg_form.
The field could be used using the `EDNX_CUSTOM_REGISTRATION_FIELDS` setting.
Based in this edx-platform [logic](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/user_authn/views/register.py#L205) 
Add this setting with some fields related to an extended custom reg form.
``` json
"EDNX_CUSTOM_REGISTRATION_FIELDS": [
{
"label": "arabicname",
"name": "arabic_name",
"type": "text"
}
],
```
Post a user with the extra_field.
Check the user was created and in the extended custom reg model.
If you add the field is also stored in the model and meta.
``` json
"extended_profile_fields": [
"arabic_name"
]
```
This dont affect anything if you dont have defined the setting `REGISTRATION_EXTENSION_FORM`.
[setting …
> feat: enable custom_reg_form capability

- eox_core/social_tpa_backends.py
This adds a generic backend based on ConfigurableOpenIdConnectAuth but
with PKCE.
This backend is inspired by the social-core way to implement PKCE.
There is a current PR in work, but for the moment, that class is not merged and accessible.
So after that is finished this has its code for `code_challenge` and `code_challenge_method`implementation.
PR: https://github.com/python-social-auth/social-core/pull/856
Please provide detailed step-by-step instructions for testing this change.
**Jira story**
https://edunext.atlassian.net/browse/FUTUREX-606
> feat: add pkce-openid-backend

- eox_core/api/data/v1/urls.py
- eox_core/api/support/urls.py
- eox_core/api/support/v1/urls.py
- eox_core/api/task_dispatcher/v1/urls.py
- eox_core/api/urls.py
- eox_core/api/v1/urls.py
- eox_core/api_schema.py
- eox_core/urls.py
`django.conf.urls.url()` was deprecated in Django 3.0, and is removed in Django 4.0+. To stay updated and be able to use the code with Quince that uses Django 4.0+, we change the `url` function to `re_path`.
The version of Django in Quince: https://github.com/openedx/edx-platform/blob/open-release/quince.master/requirements/edx/base.txt#L184 
Deprecation note: https://code.djangoproject.com/ticket/31534
Example of re_path use in other of our repositories (eox-tenant): https://github.com/eduNEXT/eox-tenant/blob/master/eox_tenant/api/urls.py
> fix: update urls in favor of re_path for deprecation

- eox_core/social_tpa_backends.py
This adds a generic backend based on ConfigurableOpenIdConnectAuth but with PKCE.
This backend is inspired in the social-core way to implement PKCE. There is a current PR in work, but for the moment, that class is not merged and accessible. So after that is finished this has it code for `code_challenge` and `code_challenge_method`implementation.  migration pr of  https://github.com/eduNEXT/eox-core/pull/255
Please provide detailed step-by-step instructions for testing this change.
Include anything else that will help reviewers and consumers understand the change.
- Does this change depend on other changes elsewhere?
- Any special concerns or limitations? For example: deprecations, migrations, security, or accessibility.
- Link to other information about the change, such as Jira issues, …
> feat: add pkce-openid-backend (#255)

- eox_core/tests/tutor/integration_test_tutor.py
This PR adds validation for the /eox-core/eox-info endpoint in the integration test
Checks:
- Integration / integration-test (<17.0.0) (pull_request)
- Integration / integration-test (<18.0.0) (pull_request)
SITE_ID = 2 is used to fix the error: django.contrib.sites.models.Site.DoesNotExist: Site match query does not exist.
When running an instance, SITE_ID is 2, so the setting was overridden so that during testing it also takes the SITE_ID = 2
https://edunext.atlassian.net/browse/DS-993
> feat: add api integration test

- CHANGELOG.md
- README.rst
- eox_core/__init__.py
- eox_core/api/v1/permissions.py
- setup.cfg
This PR adds an `ImproperlyConfigured` exception in `load_permissions` function to avoid errors during the build.
<details>
<summary>Details of error</summary>
```bash
=> ERROR [production 19/37] RUN ./manage.py lms --settings=tutor.i18n pull_plugin_translations --verbose --repository='openedx/openedx-translations' --revision='o  5.3s
------
> [production 19/37] RUN ./manage.py lms --settings=tutor.i18n pull_plugin_translations --verbose --repository='openedx/openedx-translations' --revision='open-release/redwood.1':
4.572 Traceback (most recent call last):
4.572   File "/openedx/edx-platform/./manage.py", line 106, in <module>
4.572     execute_from_command_line([sys.argv[0]] + django_args)
4.572   File "/openedx/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line …
```
> fix: add improperly configured exception in load permissions function

- .github/workflows/integration-test.yml
This PR includes the following updates:
1. **Updated Action Branch**: Changed the branch of the action that executes the integration tests to use the main branch with the latest changes. This update allows the tests to run outside the LMS container:
- `uses: eduNEXT/integration-test-in-tutor@main`
2. **Removed Unnecessary Input**: Removed the `openedx_imports_test_function_name` input, as it is no longer required with the latest changes:
- `openedx_imports_test_function_name: 'test_current_settings_code_imports'`
These changes ensure the workflow is aligned with the latest improvements and simplifies the testing process.
- Check the integration tests in the PR checks are executed successfully for tutor versions: 17.0.0, 18.0.0, and nightly
> refactor(ci): update workflow for integration tests

- .github/dependabot.yml
This PR adds the `dependabot.yml` file to perform automated upgrading to GitHub actions. The current configuration creates a Weekly PR (on Mondays) with the changes.
[AP-1514](https://edunext.atlassian.net/browse/AP-1514)
[AP-1514]: https://edunext.atlassian.net/browse/AP-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: add dependabot config for enable github action auto update`AP-1514`

- docs/how_to/users_api.rst
This PR adds the user API documentation
https://edunext.atlassian.net/browse/AP-1439
> docs: add users api docs

- .github/workflows/labeler.yml
This PR updates the versions of the workflow actions to use the MAJOR version (if possible).
[AP-1514](https://edunext.atlassian.net/browse/AP-1514)
[AP-1514]: https://edunext.atlassian.net/browse/AP-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: use major versions in workflow actions `AP-1514`

- eox_core/api/v1/serializers.py
- requirements/base.txt
- requirements/constraints.txt
- requirements/test.txt
- requirements/tox.txt
This PR removes the pycodestyle as the issue was already fixed [here](https://github.com/PyCQA/pycodestyle/issues/1090) and added a comment explaing why the django-oauth-toolkit<2.0.0 is necessary.
> chore: removed unnecessary constraints

- .github/workflows/commitlint.yml
This PR updates the `commitlint.yml` workflow to use Open edX's reusable workflow. This change is mainly to align with the platform workflows.
See the **Lint Commit Messages** job
- https://github.com/eduNEXT/eox-theming/pull/72#issuecomment-2456698858
[AP-1595](https://edunext.atlassian.net/browse/AP-1595)
[AP-1595]: https://edunext.atlassian.net/browse/AP-1595?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ci: use openedx commitlint workflow `AP-1595`

- .github/workflows/integration-test.yml
Renamed the `nightly` version in the Tutor Integration Tests Workflow to `main`. This aligns with the recent Tutor branch renaming discussed [here](https://discuss.openedx.org/t/tutor-branches-rename/14455).
- Tutor has officially renamed the `nightly` branch to `main`.  
- Updated the `nightly` tutor_version in the workflow to ensure compatibility with the new branch structure.
> ci(integration-tests-workflow): rename nightly to main in tutor_version matrix

- CHANGELOG.md
- eox_core/__init__.py
- eox_core/api/support/v1/authentication.py
- eox_core/api/support/v1/permissions.py
- eox_core/api/support/v1/views.py
- eox_core/settings/common.py
- setup.cfg
- setup.py
This PR adds a **custom authentication class** (`JWTsignedOauthAppAuthentication`) that allows authentication using a **signed JWT token** for the `OauthApplicationAPIView`.  
Your explanation is clear but a bit **wordy** and could be structured more logically for better readability. Here's a **more concise and natural version**:
When a new subscription is registered from Control Center, we need to call this `eox-core` endpoint to create the **tenant OAuth client** for the instance. However, at this stage, Control Center does **not yet have** the OAuth client credentials needed to generate a JWT token for authentication.  
This authentication mechanism allows the request to be securely made using a **signed JWT token**, eliminating the need for pre-existing credentials.  
Once the …
> feat: add JWT signed authentication for OAuth application API

- .github/workflows/integration-test.yml
- CHANGELOG.md
- eox_core/__init__.py
- setup.cfg
This PR updates the Tutor versions used in integration tests to include Tutor Teak and remove Redwood support.
> feat: add teak and remove redwood tutor versions from integration tests
