eduNEXT/eox-core

Makefile, eox_core/__init__.py, eox_core/apps.py, eox_core/settings/test.py, eox_core/tests.py, eox_core/tests/test_views.py, eox_core/urls.py, eox_core/views.py, manage.py, pytest.ini, requirements.txt, setup.cfg, setup.py
This PR adds bumpversion as a dependency. To bump the version, there is a target on the make file.
Also the eox-core/eox-info view now returns a json including the version
- Bump the minor version once
=> Semantic Version Management

eox_core/edxapp_wrapper/backends/users_h_v1.py
This PR makes the h_v1 more robust and useful
It is still a work in progress, so hang tight
=> WIP | Upgrades to the h_v1 users backend

eox_core/api/v1/views.py, eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
=> Add logging on enroll API

README.md
Missing "make dev.up" on README.md
=> Missing "make dev.up" on README.md

eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
This PR is the result of debugging a particular behavior on production for a given program
=> Making sure that if no courses are available we fail verbosely

eox_core/apps.py, eox_core/settings/common.py
Adding aws config to plugin conf to allow settings overrides
Increasing data api pagination size
@diegomillan
=> Adding aws config to plugin conf to allow settings overrides.

eox_core/api/v1/__init__.py, eox_core/api/v1/permissions.py, eox_core/api/v1/views.py, eox_core/settings/common.py, eox_core/settings/test.py
This PR adds a custom permission to decide if an API request is processed or not 
@Squirrel18 
@jfavellar90
=> Changing API permissions

eox_core/settings/aws.py, eox_core/settings/common.py, eox_core/settings/test.py
=> moving settings so they can be loaded correctly

eox_core/edxapp_wrapper/backends/enrollment_h_v1.py
This PR adds a logic to validate if an enrollment request can be applied for a given site.
=> adding org validation before enrollment

eox_core/settings/test.py
Platform test are passing with the proposed configuration here
@felipemontoya
=> defining a plugin_settings function for test env

eox_core/settings/test.py
This PR changes backends dynamically (as needed) and only over test environments, reducing the impact on platform tests.
@Squirrel18 
@felipemontoya
=> Fix platform db test failures

eox_core/api/v1/views.py, eox_core/edxapp_wrapper/backends/enrollment_h_v1.py, eox_core/edxapp_wrapper/enrollments.py
The purpose of this PR is to add missing CRUD operations to the Enrollment API:
_UPDATE ENROLLMENT_
```shell	 
curl -X PUT --header "Authorization: Bearer <AUTH_TOKEN> " -H "Accept: application/json" \
http://edx.devstack.lms:18000/eox-core/api/v1/enrollment/ --header "Content-Type: application/json" \
--data '{"course_id": "course-v1:edX+DemoX+Demo_Course", "email": "username@example.com",
"mode": "audit", "is_active": "False", "enrollment_attributes": [{"namespace": "credit", "name": "provider_id", "value": "hogwarts" }]
}'
```
_GET ENROLLMENT_
```shell	 
curl -X GET --header "Authorization: Bearer <AUTH_TOKEN> " -H "Accept: application/json" \
http://edx.devstack.lms:18000/eox-core/api/v1/enrollment/ --header "Content-Type: application/json" \
--data '{"course_id": …
```
=> Add CRUD operations in enrollment API

Makefile, eox_core/api/data/v1/urls.py, eox_core/api/v1/tests/test_enrollments.py, eox_core/edxapp_wrapper/backends/certificates_h_v1_test.py, eox_core/edxapp_wrapper/backends/enrollment_h_v1.py, eox_core/edxapp_wrapper/backends/users_h_v1_test.py, eox_core/edxapp_wrapper/enrollments.py, eox_core/settings/common.py, eox_core/settings/test.py, requirements.in, requirements.txt, setup.cfg
This PR adds and fixes code quality errors using pycodestyle
@anmrdz
=> Adding pycodestyle for code quality checks

eox_core/api/v1/serializers.py, eox_core/api/v1/tests/test_coursekey.py, eox_core/api/v1/tests/test_pre_enrollments.py, eox_core/api/v1/urls.py, eox_core/api/v1/views.py, eox_core/edxapp_wrapper/backends/coursekey_h_v1.py, eox_core/edxapp_wrapper/backends/pre_enrollment_h_v1.py, eox_core/edxapp_wrapper/enrollments.py, eox_core/edxapp_wrapper/pre_enrollments.py, eox_core/edxapp_wrapper/tests/test_pre_enrollments.py, eox_core/settings/aws.py, eox_core/settings/common.py, eox_core/settings/test.py
The purpose of this PR is to add the Pre-enrollment (Whitelistings) API:
=> Pre-enrollment API

.circleci/config.yml
This PR sets the coverage to 70%.
=> Set 70% of coverage

eox_core/api/v1/permissions.py
With this PR the token client is compared to the host. If they don't match, then it is the same as if no authorization had happened.
This is critical for multi-tenant access.
SessionAuthorization is no longer possible unless the user is_staff = true
=> Tokens should only be used in the same site as the oauth client object

eox_core/api/v1/views.py, eox_core/edxapp_wrapper/backends/users_h_v1.py
The purpose of this PR is to improve the get_user endpoint, by:
-  [x] Allow query params to be set from the request.data (Be a forgiving API) 
-  [x] Unify response with DRF Exceptions
=> Improve get endpoint in user API

AUTHORS.txt, LICENSE.txt, MANIFEST.in, eox_core/api/v1/views.py, eox_core/edxapp_wrapper/backends/certificates_h_v1_test.py, eox_core/edxapp_wrapper/backends/users_h_v1.py, eox_core/edxapp_wrapper/backends/users_h_v1_test.py
This PR solves the errors we found on V1.0.0 once it was up in production.
- Site is available for POST in enrollments
- No missing migrations
- Manifest with includes so no -e is needed in installation
=> Feedback from 1.0.0

eox_core/settings/test.py
This PR corrects the permission loading that was creating errors for the platform tests
=> Fixes the permission loading at the platform

eox_core/middleware.py
Preventing mktg redirects to empty locations
@morenol 
@cocococosti 
@felipemontoya
=> Preventing mktg redirects to empty locations

eox_core/settings/aws.py, eox_core/settings/common.py
Making the append of the LMS middleware classes optiona in the plugin
@morenol 
@cocococosti 
@felipemontoya
=> Making the append of the LMS middleware classes optiona in the plugin

eox_core/edxapp_wrapper/backends/users_h_v1_test.py
Defining all methods on the users test backend based on the original production users backend. This will fix the edxapp tests run
@morenol 
@cocococosti
=> Changes to fix edxapp tests

eox_core/admin.py
The purpose of this PR is to improve the loading times of SignupSource and LoginFailures admin views by removing duplicated queries and filters that are not used at all.
=> Improve load times of Django Admin Views

eox_core/pipeline.py
Force the execution of user_post_save_callback in order to execute the auto enrollments.
=> Add force_user_post_save_callback pipeline

eox_core/settings/aws.py, setup.py
Upgrade [sentry-sdk](https://github.com/getsentry/sentry-python/blob/master/CHANGES.md) version and enable [celery integration](https://docs.sentry.io/platforms/python/celery/)
https://stackoverflow.com/a/60947153
=> Enable celery integration for sentry

eox_core/social_tpa_backends.py
This PR adds a completely configurable OpenId Connect based backend for third party auth
=> Adding the configurable backend

.circleci/config.yml
Use cache for test in circleci.
=> Allow to use cache in circleci

.circleci/config.yml
Deploy releases to pypi on tag creation.
=> Release on tag creation

CHANGELOG.rst
In this PR I added description to the changelog for some of the last releases of this project.
=> Add more versions to the changelog.

CHANGELOG.rst, eox_core/api/data/v1/viewsets.py, eox_core/api/v1/views.py, eox_core/edxapp_wrapper/backends/bearer_authentication_j_v1.py, eox_core/edxapp_wrapper/backends/bearer_authentication_j_v1_test.py, eox_core/edxapp_wrapper/bearer_authentication.py, eox_core/settings/aws.py, eox_core/settings/common.py, eox_core/settings/test.py
Adding bearer_authentication file to edxapp_wrapper/backends and update views to use this file
=> Adding bearer_authentication

CHANGELOG.rst, eox_core/admin.py, eox_core/edxapp_wrapper/backends/users_h_v1.py, eox_core/edxapp_wrapper/backends/users_h_v1_test.py, eox_core/edxapp_wrapper/users.py
These django admin models are remove since these were included in eox-support
=> [JUNIPER GI-6]Remove loginFailures and Usersignupsource admin models

eox_core/api/data/v1/filters.py, eox_core/api/data/v1/urls.py, eox_core/api/data/v1/viewsets.py, eox_core/api/urls.py, eox_core/api/v1/urls.py, eox_core/apps.py, eox_core/cms/urls.py, eox_core/edxapp_wrapper/backends/users_j_v1.py, eox_core/middleware.py, eox_core/settings/common.py, eox_core/settings/devstack.py, eox_core/settings/production.py, eox_core/settings/test.py, eox_core/urls.py, requirements/base.in, requirements/base.txt, requirements/constraints.txt, requirements/django.txt, requirements/test.txt
=> Add django 2.2 compatibility

CHANGELOG.rst, MANIFEST.in, requirements/sentry.in, requirements/tpa.in, setup.py
This change aims to follow the OEP guidelines to dependency management.
=> Add OEP-18 Compliance

eox_core/migrations/0001_initial.py
Fix type migration file.
Error  https://stackoverflow.com/questions/52057583/python-2-3-django-migration-causes-field-parameter-type-change
solution in edx https://github.com/edx/edx-platform/pull/22115
=> Fix type migrations

CHANGELOG.rst, eox_core/__init__.py, eox_core/api/v1/permissions.py, eox_core/api/v1/tests/test_permissions.py, setup.cfg
This PR changes the way we review the auth client (or application in the dot case) for API calls
=> Updating permissions.py to accept dot and dop tokens

README.rst
There are a few instructions that need updating.
=> Update install and dependencies update instructions.

eox_core/pipeline.py, eox_core/tests/test_pipeline.py
This PR adds a pipeline function that can avoid disconnection from a TPA provider through TPA Configuration settings.
For example:
To avoid disconnection from SAML, add the following to `Other config str` in your SAMLConfiguration:
"BACKEND_OPTIONS": { "disableDisconnectPipeline":true },
Now, to avoid disconnection from an Oauth2Provider, add the same setting to `Other settings` in your
Oauth2Provider.
It's recommended to place this function at the beginning of the pipeline.
=> Added pipeline step to avoid disconnection from TPA provider

eox_core/api/v1/serializers.py, eox_core/api/v1/tests/test_grades.py, eox_core/api/v1/urls.py, eox_core/api/v1/views.py, eox_core/api_schema.py
This PR introduces a new endpoint `eox-core/api/v1/grade` to retrieve Grade data of a user from a given course.
=> Add Grades Endpoint

eox_core/pipeline.py, eox_core/tests/test_pipeline.py
This PR checks when linking to a TPA provider that the user's information from the LMS (ie. email, etc) matches with the information returned by the TPA provider (ie. email, etc). If the information does not match, then an Exception will be raised.
This step will avoid linking/authenticating accounts with inconsistencies with their user information.
=> Added pipeline step to check if user's information matches

CHANGELOG.rst, eox_core/api/v1/serializers.py, eox_core/api/v1/tests/test_grades.py, eox_core/api/v1/views.py
This PR includes the swagger documentation for Grades API added on #128.
=> Add documentation for the Grades API.

CHANGELOG.rst, eox_core/api/v1/views.py, eox_core/tests/integration/README.rst, eox_core/tests/integration/test_enrollment_integration.py, eox_core/tests/integration/test_grade_integration.py, tox.ini
This PR adds integration tests for the Grades API introduced on #128
=> Add integration tests for the Grades API

eox_core/pipeline.py
This removes the usage of auth_entry in the force_user_post_save_callback pipeline step.
I think that it is safe to remove that and depend on the is_new parameter to decide if we want to send that signal.
=> fix: Force the callback of post_save when the user is new

eox_core/logging.py, eox_core/pipeline.py
This PR adds the logging_pipeline_step function that logs an exception with the information from the failed pipeline step.
=> feat(MTPS): Add more information to pipeline steps

eox_core/api/task_dispatcher/tests/test_views.py, eox_core/api/task_dispatcher/v1/urls.py, eox_core/api/task_dispatcher/v1/views.py, eox_core/settings/common.py, eox_core/urls.py
This PR includes a new endpoint that allows to run any arbitrary celery task that is registered in the worker and included in a setting.
=> Add a new endpoint to to run celery tasks

eox_core/api/support/urls.py, eox_core/api/support/v1/__init__.py, eox_core/api/support/v1/permissions.py, eox_core/api/support/v1/serializers.py, eox_core/api/support/v1/tests/test_permissions.py, eox_core/api/support/v1/urls.py, eox_core/api/support/v1/views.py, eox_core/edxapp_wrapper/backends/users_j_v1.py, eox_core/edxapp_wrapper/users.py, eox_core/urls.py
This feature adds an endpoint to safely remove an account from the platform.
This new endpoint is intended to be used in the CLI.
=> feat: Remove User endpoint.

eox_core/pipeline.py, eox_core/tests/test_pipeline.py
This PR adds two pipeline steps used during the TPA process to create signup sources associated with the current user and site.
**Motivation**
https://3.basecamp.com/3966315/buckets/8050706/todos/3695494462
**How to test**
I've been testing the pipeline steps with this custom pipeline using a google provider:
```
"SOCIAL_AUTH_GOOGLE_OAUTH2_PIPELINE": [
"third_party_auth.pipeline.parse_query_params",
"social_core.pipeline.social_auth.social_details",
"social_core.pipeline.social_auth.social_uid",
"social_core.pipeline.social_auth.auth_allowed",
"social_core.pipeline.social_auth.social_user",
"social_core.pipeline.user.get_username",
"third_party_auth.pipeline.set_pipeline_timeout",
"eox_tenant.pipeline.safer_associate_by_email",
"social_core.pipeline.user.create_user", …
```
=> feat: add TPA pipeline steps used to register signupsources

eox_core/api/support/v1/views.py, eox_core/api/task_dispatcher/v1/views.py, eox_core/api/v1/views.py
Decorate main methods which change or create information in order to register those actions
=> And/decorate APIs

README.rst
Concerns: what can we remove from the read me that might be deprecated? or what can we add that's missing
=> docs: update documentation with newer info (after juniper)

CHANGELOG.rst, eox_core/api/v1/views.py
=> refactor: Update action names in EdxappPreEnrollment view

eox_core/social_tpa_backends.py
In a multi tenancy context uniquely identifying social associations by `user_id` and provider becomes insufficient. This PR attempts to alleviate the current situation by prepending a slug included in the provider configuration. This way each OIDC configuration would have their own namespace.
To ease the deployment of the feature, previous associations that lack the slug would be updated at login time. Once all the existing associations have been updated, is possible to forbid any new association that doesn't include an slug.
The whole feature can be enabled on a per site basis.
=> feat(TPA): override get_user_id to prepend a slug to the uid.

CHANGELOG.rst, docs/decisions/0001-include-slug-in-uid.rst
Include the Architectural Decision Record for the changes made #153
=> docs: add ADR and update changelog

CHANGELOG.rst, eox_core/api/v1/serializers.py, eox_core/api/v1/tests/test_users.py, eox_core/edxapp_wrapper/backends/users_j_v1.py, eox_core/settings/common.py, eox_core/utils.py, requirements/base.txt, requirements/constraints.txt, requirements/test.in, requirements/test.txt, requirements/tox.txt
This PR allows to include the profile fields when creating a user
The following microsite settings are used to validate the fields sent in the request: **REGISTRATION_EXTRA_FIELDS**, **extended_profile_fields**, and **EDNX_CUSTOM_REGISTRATION_FIELDS**
For more context, you can check the doc on [custom registrations fields](https://docs.google.com/document/d/1adLna0aGe4MAXtlSRKKwI2TPvtv0AbQQl_qMVxJfDPI/edit)
**Example:**
Suppose a microsite has the following settings
```
"EDNX_CUSTOM_REGISTRATION_FIELDS": [
{
"label": "Tipo de Documento",
"name": "type_document",
"options": [
"DNI",
"PASAPORTE",
"CARNET DE EXTRANJERIA",
"CEDULA DE IDENTIDAD"
],
"type": "select"
},
{
"label": "Numero de Documento",
"name": "personal_id",
"type": "text"
},
{
"label": "Celular",
"name": "mobile",
"type": …
```
=> feat: Allow adding profile fields when creating a user

CHANGELOG.rst, eox_core/api/v1/views.py, eox_core/api_schema.py
This PR adds the swagger documentation for the user API
https://openedx.je.edunextstage.net/eox-core/api-docs/
=> feat: add User API documentation

CHANGELOG.rst, eox_core/edxapp_wrapper/backends/courses_h_v1.py, eox_core/edxapp_wrapper/courses.py
This PR adds a new function getter to the course backend. It's nothing new, just returning CourseOverview model.
=> feat: add course overview function getter

package-lock.json
Tests are failing to install the dependencies on the `3.8-buster-node` python image from circleci.
I've simply recreated the package-lock.json. No dependency changes were made.
=> Fix failing tests due to old package.json

eox_core/edxapp_wrapper/backends/users_l_v1_test.py, eox_core/settings/test.py
This PR adds lilac backends to test.py settings, fixing [this](https://github.com/eduNEXT/edunext-platform/runs/4121816426?check_suite_focus=true#step:8:694) kind of errors
=> test: add lilac backends to test settings

CHANGELOG.rst, eox_core/edxapp_wrapper/backends/third_party_auth_l_v1.py, eox_core/settings/common.py
This PR creates a lilac compatible backend for TPA.
Please provide detailed step-by-step instructions for testing this change.
=> fix: add missing backend for third party auth

CHANGELOG.rst, requirements/sentry.in
This PR upgrades sentry-sdk to latest compatible release 1.5.1
Just a chore.
=> chore: upgrade sentry-sdk to latest release

eox_core/edxapp_wrapper/backends/users_l_v1.py
=> fix: add missing `generate_password` import

.github/workflows/bump_version.yml
This commit solves the issue with commit permissions.
- Replace create commit with create a pull request.
=> fix: replace create commit with create pr

requirements/base.in
I tried to install this eox-core in nelp koa lms but I couldn't after I targeted the  5.04 version.
This because `...backends/users_l_v1.py` in 5.1 add `openedx_events`
import.
https://github.com/eduNEXT/eox-core/blob/v5.1.0/eox_core/edxapp_wrapper/backends/users_l_v1.py#L42
Try in your devstack or local container to install only eox-core in a koa release. And look at the behavior of your lms-logs.
Devstack:
`make lms-logs`
**Before**:
```
edx.devstack-koa.master.lms       |   @detail_route(url_path='programs/(?P<program_uuid>[^/]+)')
edx.devstack-koa.master.lms       | 
edx.devstack-koa.master.lms       | Exception in thread django-main-thread:
edx.devstack-koa.master.lms       | Traceback (most recent call last):
edx.devstack-koa.master.lms       |   File …
```
=> chore: add openedx_events to requirements.

.github/workflows/commitlint.yml, commitlint.config.js
This PR update commitlint workflow to use config-conventional, this config-conventional settings will be loaded as a default fallback avoid use commitlint-config.js.
```bash
[
'build',
'chore',
'ci',
'docs',
'feat',
'fix',
'perf',
'refactor',
'revert',
'style',
'test'
];
```
To test, you can make a commit on this PR with:
* FIX: testing commitlint -> output workflow should show an error (FIX)
* Fix: testing commitlint -> output workflow should show an error (Fix)
* testing commitlint -> output workflow should show an error (have to use conventional commit)
After you test it, please make a `reset hard` at last commit `ci: update workflows commitlint and rm commitlint.config file`.
* Commitlint Github Action: https://github.com/wagoid/commitlint-github-action
* …
=> ci: update workflows commitlint and rm commitlint.config file 

eox_core/edxapp_wrapper/backends/certificates_m_v1.py, eox_core/edxapp_wrapper/backends/coursekey_m_v1.py, eox_core/edxapp_wrapper/backends/courses_h_v1.py, eox_core/settings/common.py, eox_core/settings/production.py
This PR remove try except from imports in backends and correct platform paths.
Modified Backends:
- certificates_m_v1
- coursekey_m_v1
- courses_h_v1
1. Use this strain.yml file to create a mango project
```bash
STRAIN_NAME: mango
STRAIN_TUTOR_VERSION: v13.3.1
DEV_PROJECT_NAME: mango_dev
LOCAL_PROJECT_NAME: mango_local
CMS_HOST: studio.mango.edunext.link
LMS_HOST: lms.mango.edunext.link
PLATFORM_NAME: Distro mango
STRAIN_TUTOR_PLUGINS:
- REPO: tutor-contrib-edunext-distro
VERSION: v2.3.0
EGG: tutor-contrib-edunext-distro==v2.3.0
PACKAGE_NAME: distro
PROTOCOL: ssh
- REPO: tutor-forum
VERSION: 3a5cfac9e68dbac61b8abe4b6e15e023cbb3fee0
EGG: tutor-forum==3a5cfac9e68dbac61b8abe4b6e15e023cbb3fee0
PATH: overhangio
PACKAGE_NAME: forum
STRAIN_EXTRA_COMMANDS:
- APP: 'tutor'
COMMAND: 'distro …
```
=> fix: remove try except and correct platform paths

.github/workflows/bump_version.yml, CHANGELOG.md
This PR update the CHANGELOG file and the bumpversion workfloy to publish the changelog when a PR is merge.
=> (DS-338) fix(ci): update bumpversion workflow to make changelog publish

docs/resources/eox-core-test.postman_collection.json, eox_core/api/support/v1/views.py, eox_core/api/task_dispatcher/v1/views.py, eox_core/api/v1/views.py, requirements/base.in
This PR allows you to request with a JWT token.
1. Install the plugin.
2. Follow the test case document; only the API is enough (File: https://docs.google.com/document/d/1gaQyHBGDDkvy_NsFw07MRV6uI2R49CeWCDHzTVi_TiI/edit?usp=sharing)
(In this PR, I changed the postman collection to make the requests with JWT)
This PR is related to #254 and the issue #249
=> feat: add support for JWT authentication DS-703

.github/workflows/integration-test.yml, eox_core/tests/tutor/integration.sh
This PR adds the configuration files to integrate github action https://github.com/eduNEXT/integration-test-in-tutor
Checks:
- Integration / integration-test (<17.0.0) (pull_request)
- Integration / integration-test (<18.0.0) (pull_request)
https://edunext.atlassian.net/browse/DS-963
=> feat: add github action integration

README.rst, docs/help_for_devs/0001-include-test-cases-files.rst, docs/how_to/api.rst, docs/how_to/middleware.rst, docs/how_to/middlewere.rst, docs/how_to/pipeline.rst, eox_core/apps.py, eox_core/settings/common.py, eox_core/settings/devstack.py, eox_core/settings/production.py, eox_core/settings/test.py
This PR improves the repository documentation for a better understanding of the eox-core plugin.
For repo description:
> Open edX plugin to extend the core functionality
[JIRA](https://edunext.atlassian.net/browse/DS-971)
=> docs: improve README and hows-to

.github/workflows/integration-test.yml, CHANGELOG.md, README.rst, eox_core/__init__.py, requirements/base.txt, requirements/pip-tools.txt, requirements/test.txt, requirements/tox.txt, setup.cfg
This PR adds support to sumac.
1. Updated the requirements to fit the latest release
2. Updated docs and tests for tutor 19
1. Install a brand new environment using Tutor 19
2. Install eox-tenant and eox-core using this branch
3. Run the test cases descibed [here ](https://docs.google.com/document/d/1gaQyHBGDDkvy_NsFw07MRV6uI2R49CeWCDHzTVi_TiI/edit?tab=t.0)
4. 
Jira issue related: https://edunext.atlassian.net/jira/software/c/projects/AP/boards/40?assignee=712020%3A8f85d875-d46f-49c9-96f5-5ca72ca7fcc7&selectedIssue=AP-1581
=> perf: added sumac support
